### ISSUE TITLE
Persistent sounds bug

### ISSUE THREAD

**Issue by derpsderps69** [airmash-refugees/airmash-frontend#6]
Most likely candidate is Howler.js via b8549af9321670a21e78cc7c50b0c6728273e10e

Going to have a go at finding a way to diff the replaced and original libs

**Comment by congratulatio** [comment]
Thanks derps, I've put the original howler.js back in the meantime (https://github.com/airmash-refugees/airmash-frontend/commit/deb6afe878c3b83604d092d37c864f3c44d11ff1) and deployed that to [airmash.online](https://airmash.online)

**Comment by congratulatio** [comment]
Fixed in https://github.com/airmash-refugees/airmash-frontend/commit/be3d692a2fa1634a582f716080f48aa4657c0d7e

**Comment by derpsderps69** [comment]
sadtimes ;(  Still getting this on test.a.o

This time it was a missile thruster not a heli

**Comment by congratulatio** [comment]
I was getting this the other day too but it seems okay now, no idea why. Can you still reproduce this?

**Comment by congratulatio** [comment]
I'd mistakenly patched the files in `lib` rather than `dist`, this updated patch should sort it out.
